### ISSUE TITLE
윈도우 외에 환경에서 디렉토리 이름 버그가 있네요

### ISSUE THREAD

**Issue by qfourca** [codingbotPark/react-styledcomt-generator#3]
윈도우 외에 환경에서 디렉토리 이름 버그가 있네요
<img width="618" alt="스크린샷 2023-01-09 오후 4 15 26" src="https://user-images.githubusercontent.com/80884472/211257074-10116ad0-9cbc-4288-bbd5-031068a7abce.png">

**Comment by codingbotPark** [comment]
해결하겠습니다
