### ISSUE TITLE
신고합니다...

### ISSUE THREAD

**Issue by park56** [codingbotPark/react-styledcomt-generator#7]
진짜 이따구로 만들거면 버전 0.0.0.0.01부터 하던가, 지웠다 깔기만 수십번을 하네요..;; 지니짜.. 신고합니노

**Comment by ksh5324** [comment]
인정합니다

**Comment by park56** [comment]
니가뭔데 ;;

**Comment by ksh5324** [comment]
박성한 조용해라 그냥 지우면서 써

**Comment by park56** [comment]
근데 내가 봤을 떄 그냥 제작자가 확장 앱 이름부터 이상하게 쓴거부터 해서
답이없음

**Comment by park56** [comment]
# 내가 좋은 아이디어로 이름추천해줬는데 그냥 개무시하고 개구린 이름 붙여서 개꼴받는데 옆자리에 얼굴보면 미치겠음 한대 치고싶기도 하고

**Comment by park56** [comment]
제작자 그냥 씹는데?

**Comment by ksh5324** [comment]
@park56 돼지쉨
